#!/bin/bash 
######################################
#            Shell script            #
# Author: H.L.                       #
# TPL Version: 0.1                   #
######################################

#========================Global variables
APPVER="0.1b"
MYDIR=$0 && FILENAME=$(basename $MYDIR) && MYREALDIR=$(readlink $MYDIR)
if [ ! -z $MYREALDIR ]; then FILENAME=$(basename $MYREALDIR) &&  MYDIR=$MYREALDIR; fi;
MYDIR=${MYDIR%%/$FILENAME}
#=======================Include base library

. /etc/system.conf
. $libROOT/functions



